USE BDEX3_REDESOCIAL;
#EX1
SELECT * FROM usuarios;
#EX2
SELECT NOME_USUARIO, SOBRENOME, EMAIL
FROM USUARIOS;
#EX3
SELECT NOME_GRUPO, DESCRICAO FROM GRUPOS;
#EX4
SELECT ID_POST, TEXTO, IMAGEM, DATA_HORA, NOME_USUARIO
FROM postagens as P
join usuarios on p.usuario = id_usuario;
#EX5 - Listar o nome dos usuários e a quantidade de postagens que cada um fez.
SELECT ID_USUARIO,NOME_USUARIO, count(*) as qtd_postagens
FROM POSTAGENS AS P
JOIN USUARIOS AS u ON ID_USUARIO = P.USUARIO
GROUP BY nome_usuario;
#EX6 - Mostrar os nomes dos usuários que fizeram comentários em 2024.
SELECT NOME_USUARIO, ID_COMENTARIO, DATAHORA
FROM USUARIOS AS U
JOIN COMENTARIOS AS C ON ID_USUARIO = C.ID_COMENTARIO;
#EX7 - Listar todos os grupos, ordenados pelo nome do grupo de A a Z.
SELECT ID_GRUPO,NOME_GRUPO
FROM GRUPOS
ORDER BY NOME_GRUPO ASC;
#EX8
SELECT NOME_GRUPO,DESCRICAO
FROM GRUPOS
WHERE DESCRICAO LIKE '%Tecnologia';
#EX9 
SELECT NOME_USUARIO,ID_COMENTARIO,C.TEXTO,DATAHORA,ID_POST
FROM USUARIOS AS U
JOIN POSTAGENS AS P ON ID_USUARIO = P.ID_POST
JOIN COMENTARIOS AS C ON P.ID_POST = C.ID_COMENTARIO;
#EX10
SELECT ID_POST,P.TEXTO AS POSTAGEMTEXTO,C.TEXTO AS COMENTARIO,ID_COMENTARIO, COUNT(ID_COMENTARIO) AS QTD_COMENTARIOS
FROM POSTAGENS AS P
JOIN COMENTARIOS AS C ON P.USUARIO = C.USUARIO
GROUP BY P.ID_POST;
#EX11
SELECT NOME_USUARIO, SEGUIDOR, COUNT(SU.SEGUIDOR)
FROM USUARIOS AS U
JOIN seguidores_usuarios AS SU
ORDER BY NOME_USUARIO
